FTB-Community/force-app/main/default/objects/FTB_ErrorLog__c/FTB_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Custom Object to trace server errors</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>FTBERR-{0000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_ErrorLog__c/fields/FTB_ErrorCode__c.field-meta.xml
<CustomField>
    <fullName>FTB_ErrorCode__c</fullName>
    <description>This fields contains the error code to easily categorize errors</description>
    <label>Error Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_ErrorLog__c/fields/FTB_ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>FTB_ErrorDescription__c</fullName>
    <description>This fields contains the error description</description>
    <label>Error Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_ErrorLog__c/fields/FTB_Request__c.field-meta.xml
<CustomField>
    <fullName>FTB_Request__c</fullName>
    <description>This fields contains the request when a web service is invoked</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_ErrorLog__c/fields/FTB_Response__c.field-meta.xml
<CustomField>
    <fullName>FTB_Response__c</fullName>
    <description>This fields contains the response of the web service invoked</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_ErrorLog__c/fields/FTB_Service__c.field-meta.xml
<CustomField>
    <fullName>FTB_Service__c</fullName>
    <description>This fields represents the service being called from the client</description>
    <label>Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_UTL_ErrorLog.cls
/**@frpanico 2023-01-05
 * Utility Class for the Erorr Log Custom Object
 * It is used to trace runtime server errors
 */
public with sharing class FTB_UTL_ErrorLog extends FTB_UTL_Utils 
{
    public FTB_UTL_ErrorLog(String service, String errorCode, String errorDescription)
    {
        insertSObject(new FTB_ErrorLog__c(FTB_Service__c = service,
            FTB_ErrorCode__c = errorCode, 
            FTB_ErrorDescription__c = errorDescription));
    }
    public FTB_UTL_ErrorLog(String service, String errorCode, String errorDescription, String request, String response)
    {
        insertSObject(new FTB_ErrorLog__c(FTB_Service__c = service, 
            FTB_ErrorCode__c = errorCode, 
            FTB_ErrorDescription__c = errorDescription,
            FTB_Request__c = request,
            FTB_Response__c = response));   
    }

}