FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/FTB_Player__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register player to select during championship</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_FullName__c.field-meta.xml
<CustomField>
    <fullName>FTB_FullName__c</fullName>
    <formula>UPPER(FTB_FirstName__c) &amp; &quot; &quot; &amp;  UPPER(FTB_LastName__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Position__c.field-meta.xml
<CustomField>
    <fullName>FTB_Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Score__c.field-meta.xml
<CustomField>
    <fullName>FTB_Score__c</fullName>
    <label>Score (AVG)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Team__c.field-meta.xml
<CustomField>
    <fullName>FTB_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>FTB_Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>FTB_Players</relationshipName>
    <type>Lookup</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/FTB_Session__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track user session</description>
    <label>User Session</label>
    <nameField>
        <displayFormat>FTBS -{00000000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_SessionId__c.field-meta.xml
<CustomField>
    <fullName>FTB_SessionId__c</fullName>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>FTB_Session</relationshipLabel>
    <relationshipName>FTB_Session</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Loss__c.field-meta.xml
<CustomField>
    <fullName>FTB_Loss__c</fullName>
    <label>Loss</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_ShortName__c.field-meta.xml
<CustomField>
    <fullName>FTB_ShortName__c</fullName>
    <label>Short Name</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Win__c.field-meta.xml
<CustomField>
    <fullName>FTB_Win__c</fullName>
    <label>Win</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/classes/FTB_QR_Team.cls
/*@frpanico 
 * Query class for the Team Custom Object
 * This class holds all the useful query for the object
 */
public with sharing class FTB_QR_Team 
{
    public static List<FTB_Team__c> getTeamWithPlayersByUserSession(String sessionId)
    {
        return readTeam
        (
            [SELECT Id, 
            Name,
            FTB_ShortName__c,
            FTB_Ranking__c,
            FTB_Win__c,
            FTB_Loss__c, 
            FTB_Championship__c,
            (SELECT Id,
            FTB_FullName__c,
            FTB_Score__c,
            FTB_Position__c
            FROM FTB_Players__r)
            FROM FTB_Team__c 
            WHERE FTB_User__c IN (Select FTB_User__c FROM FTB_Session__c WHERE FTB_SessionId__c = :sessionId)]
        );
    }


    private static List<FTB_Team__c> readTeam(List<FTB_Team__c> teamList)
    {
        SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.READABLE, teamList);
        return securityDecision.getRecords();
    }
}