FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/FTB_Player__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register player to select during championship</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Team__c.field-meta.xml
<CustomField>
    <fullName>FTB_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>FTB_Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>FTB_Players</relationshipName>
    <type>Lookup</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/FTB_Session__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track user session</description>
    <label>User Session</label>
    <nameField>
        <displayFormat>FTBS -{00000000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_SessionId__c.field-meta.xml
<CustomField>
    <fullName>FTB_SessionId__c</fullName>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>FTB_Session</relationshipLabel>
    <relationshipName>FTB_Session</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/classes/FTB_QR_TeamTest.cls
/**@frpanico
 * Test class for FTB_QR_Team
 */
@isTest
public with sharing class FTB_QR_TeamTest
{
    @TestSetup
    static void setup()
    {
        List<FTB_User__c> userList = FTB_UTL_DataFactory.createUser(true, 1);
        List<FTB_Championship__c> championshipList = FTB_UTL_DataFactory.createChampionships(true, 1);
        List<FTB_Team__c> teamList = FTB_UTL_DataFactory.createTeam(false, 1, championshipList[0].Id);
        teamList[0].FTB_User__c = userList[0].Id;
        insert teamList;
        List<FTB_Player__c> playerList = FTB_UTL_DataFactory.createPlayers(false, 1);
        playerList[0].FTB_Team__c = teamList[0].Id;
        insert playerList;
        FTB_UTL_DataFactory.createSession(true, 1, userList[0].Id);
    }
    @isTest
    static void getTeamWithPlayersByUserSessionTest()
    {
        List<FTB_Session__c> sessionList = [SELECT Id,FTB_SessionId__c FROM FTB_Session__c];
        Test.startTest();
            List<FTB_Team__c> result = FTB_QR_Team.getTeamWithPlayersByUserSession(sessionList[0].FTB_SessionId__c);
        Test.stopTest();
        System.assertEquals(true, !result.isEmpty(), 'Team not found');
    }
}