FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/classes/FTB_UTL_TeamTest.cls
/**@frpanico
 * Test class for FTB_UTL_Team
 */
@isTest
public with sharing class FTB_UTL_TeamTest
{
    @TestSetup
    static void setup()
    {
        List<FTB_User__c> userList = FTB_UTL_DataFactory.createUser(true, 1);
        List<FTB_Championship__c> championshipList = FTB_UTL_DataFactory.createChampionships(true, 1);
        List<FTB_Team__c> teamList = FTB_UTL_DataFactory.createTeam(false, 2, championshipList[0].Id);
        teamList[0].FTB_User__c = userList[0].Id;
        teamList[1].FTB_User__c = userList[0].Id;
        insert teamList;  
    }
    @isTest
    static void getSetIdFromListTest()
    {
        List<FTB_Team__c> teamList = [SELECT Id FROM FTB_Team__c];
        Test.startTest();
            Set<String> result = FTB_UTL_Team.getSetIdFromList(teamList);
        Test.stopTest();
        System.assertEquals(true, !result.isEmpty(), 'Conversion not succeded');
    }    
}