FTB-Community/force-app/main/default/objects/FTB_CMT_Configurations__mdt/FTB_CMT_Configurations__mdt.object-meta.xml
<CustomObject>
    <description>FTB Custom Metadata Type for component configurations</description>
    <label>Configuration</label>
    <pluralLabel>Configurations</pluralLabel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_CMT_Configurations__mdt/fields/FTB_Component__c.field-meta.xml
<CustomField>
    <fullName>FTB_Component__c</fullName>
    <label>Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FtbStartPage</fullName>
                <default>true</default>
                <label>FtbStartPage</label>
            </value>
            <value>
                <fullName>FtbLogin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_CMT_Configurations__mdt/fields/FTB_Message__c.field-meta.xml
<CustomField>
    <fullName>FTB_Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_LCR_Utils.cls
/**@frpanico 2022-02-06
 * FTB
 * Controller for
 * LWC ftbUtils
 */
public with sharing class FTB_LCR_Utils extends FTB_UTL_Utils
{

    @AuraEnabled
    public static String getConfiguration(String componentName)
    {
        FTB_WRP_Utils.ConfigurationWrapper wrpConfig = new FTB_WRP_Utils.ConfigurationWrapper();
        List<FTB_CMT_Configurations__mdt> configurations = FTB_CMT_Configurations__mdt.getAll().values();
        for(FTB_CMT_Configurations__mdt	configuration : configurations)
        {
            if(configuration.FTB_Component__c.equalsIgnoreCase(componentName))
            {
                wrpConfig.message = configuration.FTB_Message__c;
                break;
            }
        }
        /* Utility log */
        System.debug(loggingLevel.DEBUG,'Wrapped configuration: ' + JSON.serialize(wrpConfig));
        /* A string is returned since the wrapped object
        * Since the wrapped object is not recognized
        * by the client
        */
        return JSON.serialize(wrpConfig);
    }


}