FTB-Community/force-app/main/default/objects/FTB_Session__c/FTB_Session__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track user session</description>
    <label>User Session</label>
    <nameField>
        <displayFormat>FTBS -{00000000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FTB_IsActive__c</fullName>
    <formula>IF(NOT(ISBLANK(FTB_ClosedDateTime__c)), false,(NOW() - LastModifiedDate) &lt; 2.4 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_SessionId__c.field-meta.xml
<CustomField>
    <fullName>FTB_SessionId__c</fullName>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>FTB_Session</relationshipLabel>
    <relationshipName>FTB_Session</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/classes/FTB_UTL_Login.cls
/**@frpanico
 * Utility Class for the Login
 */
public with sharing class FTB_UTL_Login extends FTB_UTL_Utils
{
    /**@frpanico
     * This method generate user session if none active is existing
     */
    public FTB_Session__c generateUserSession(String userId, String username)
    {
        FTB_Session__c newSession = new FTB_Session__c();
        List<FTB_Session__c> existingSession = [SELECT FTB_SessionId__c FROM FTB_Session__c WHERE FTB_User__c = :userId AND FTB_IsActive__c = true];
        if(!existingSession.isEmpty())
        {
            return existingSession[0];
        }
        newSession.FTB_User__c = userId;
        newSession.FTB_SessionId__c = generateSessionId(username);
        
        return newSession;
    }
}