FTB-Community/force-app/main/default/objects/FTB_Session__c/FTB_Session__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track user session</description>
    <label>User Session</label>
    <nameField>
        <displayFormat>FTBS -{00000000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>FTB_Session</relationshipLabel>
    <relationshipName>FTB_Session</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_User__c/fields/FTB_Username__c.field-meta.xml
<CustomField>
    <fullName>FTB_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_UTL_LoginTest.cls
/**@frpanico
 * Test class for FTB_UTL_LoginTest
 */
@isTest
public with sharing class FTB_UTL_LoginTest
{
    @TestSetup
    static void setup()
    {
        FTB_UTL_DataFactory.createUser(true, 1);    
    }
    @isTest
    static void generateUserSessionTest()
    {
        List<FTB_User__c> userList = [SELECT FTB_Username__c FROM FTB_User__c];
        FTB_UTL_Login testClass = new FTB_UTL_Login();
        Test.startTest();
            FTB_Session__c resultOne = testClass.generateUserSession(userList[0].Id, userList[0].FTB_Username__c);
            insert resultOne;
            FTB_Session__c resultTwo = testClass.generateUserSession(userList[0].Id, userList[0].FTB_Username__c);
        Test.stopTest();
        System.assertEquals(true, resultOne.Id == resultTwo.Id, 'Session not generated correctly');
    }
}