FTB-Community/force-app/main/default/objects/FTB_Calendar__c/FTB_Calendar__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championship game schedule and pairings</description>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Calendars</relationshipLabel>
    <relationshipName>FTB_Calendars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Pairings__c.field-meta.xml
<CustomField>
    <fullName>FTB_Pairings__c</fullName>
    <label>Pairings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_UTL_Calendar.cls
/**@frpanico 2023-01-04
 * Utility Class for the Calendar Custom Object
 */
public with sharing class FTB_UTL_Calendar extends FTB_UTL_Utils
{
    private static final String HOME_SIGN = 'VS';
    private static final String AWAY_SIGN = '@';


    public static FTB_WRP_Utils.HomePageHomeCalendar getNextOpponent(FTB_Calendar__c calendar, FTB_Team__c singleTeam)
    {
        FTB_WRP_Utils.HomePageHomeCalendar result = new FTB_WRP_Utils.HomePageHomeCalendar();
        if(singleTeam.FTB_Championship__c == calendar.FTB_Championship__c)
        {
            result.championshipId = singleTeam.FTB_Championship__c;
            for(FTB_WRP_Utils.CalendarObj calendarObj : getPairings(calendar))
            {
                if(calendarObj.homeId.equalsIgnoreCase(singleTeam.Id))
                {
                    result.homeAway = 'VS';
                    result.nextOpponent = calendarObj.away;       
                }
                else if(calendarObj.awayId.equalsIgnoreCase(singleTeam.Id))
                {
                    result.homeAway = '@';
                    result.nextOpponent = calendarObj.home;       
                }
            }       
        }
        return result;
    }
    /* To be completed */
    private static List<FTB_WRP_Utils.CalendarObj> getUserTeamsPairings(List<FTB_Team__c> teamList, FTB_Calendar__c calendar)
    {
        List<FTB_WRP_Utils.CalendarObj> result = new List<FTB_WRP_Utils.CalendarObj>(); 
        Set<String> teamsId = FTB_UTL_Team.getSetIdFromList(teamList);
        return result;
    }
    private static List<FTB_WRP_Utils.CalendarObj> getPairings(FTB_Calendar__c calendar)
    {
        List<FTB_WRP_Utils.CalendarObj> result = new List<FTB_WRP_Utils.CalendarObj>();
        if(String.isNotBlank(calendar?.FTB_Pairings__c))
        {
            result = (List<FTB_WRP_Utils.CalendarObj>) JSON.deserialize(calendar?.FTB_Pairings__c, List<FTB_WRP_Utils.CalendarObj>.class);
        }
        return result;
    } 
    
}