FTB-Community/force-app/main/default/objects/FTB_Calendar__c/FTB_Calendar__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championship game schedule and pairings</description>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Calendars</relationshipLabel>
    <relationshipName>FTB_Calendars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_EndDate__c.field-meta.xml
<CustomField>
    <fullName>FTB_EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_NumberOfGames__c.field-meta.xml
<CustomField>
    <fullName>FTB_NumberOfGames__c</fullName>
    <label>Number Of Games</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Pairings__c.field-meta.xml
<CustomField>
    <fullName>FTB_Pairings__c</fullName>
    <label>Pairings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_RealPairings__c.field-meta.xml
<CustomField>
    <fullName>FTB_RealPairings__c</fullName>
    <label>Real Pairings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_StartDate__c.field-meta.xml
<CustomField>
    <fullName>FTB_StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Loss__c.field-meta.xml
<CustomField>
    <fullName>FTB_Loss__c</fullName>
    <label>Loss</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Win__c.field-meta.xml
<CustomField>
    <fullName>FTB_Win__c</fullName>
    <label>Win</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_QR_Championship.cls
/**@frpanico
 * Query class for the Championship Custom Object
 * This class holds all the useful query for the object
 */
public with sharing class FTB_QR_Championship
{

    public static List<FTB_Championship__c> getChampionshipsWithTeamsByIdSet(Set<Id> championshipIds)
    {
        return readChampionship
        (
            [SELECT Id, 
            Name, 
            (SELECT Name, FTB_Championship__c, FTB_Win__c, FTB_Loss__c, FTB_Ranking__c FROM FTB_Teams__r ORDER BY FTB_Ranking__c ASC),
            (SELECT FTB_Championship__c,FTB_Pairings__c, FTB_RealPairings__c, FTB_NumberOfGames__c FROM FTB_Calendars__r 
                WHERE FTB_StartDate__c <= TODAY AND FTB_EndDate__c > TODAY) 
            FROM FTB_Championship__c 
            WHERE Id IN :championshipIds]
        );
    }

    private static List<FTB_Championship__c> readChampionship(List<FTB_Championship__c> championshipList)
    {
        SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.READABLE, championshipList);
        return securityDecision.getRecords();
    }
}