FTB-Community/force-app/main/default/objects/FTB_Calendar__c/FTB_Calendar__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championship game schedule and pairings</description>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Calendars</relationshipLabel>
    <relationshipName>FTB_Calendars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Pairings__c.field-meta.xml
<CustomField>
    <fullName>FTB_Pairings__c</fullName>
    <label>Pairings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/classes/FTB_UTL_CalendarTest.cls
/**@frpanico
 * Test class for FTB_UTL_Calendar
 */
@isTest
public with sharing class FTB_UTL_CalendarTest
{
    @TestSetup
    static void makeData()
    {
        List<FTB_Championship__c> championshipList = FTB_UTL_DataFactory.createChampionships(true, 1);
        List<FTB_User__c> userList = FTB_UTL_DataFactory.createUser(true, 1);
        List<FTB_Team__c> teamList = FTB_UTL_DataFactory.createTeam(false, 2, championshipList[0].Id);
        teamList[0].FTB_User__c = userList[0].Id;
        teamList[1].FTB_User__c = userList[0].Id;
        insert teamList;
        List<FTB_Calendar__c> calendarList = FTB_UTL_DataFactory.createCalendar(false, 1, championshipList[0].Id);

        List<Map<String,String>> pairings = new List<Map<String,String>>{
            new Map<String,String>{'home' => teamList[0].Id, 
                'homeId' => teamList[0].id, 
                'away' => teamList[1].Id,
                'awayId' => teamList[1].id},
            new Map<String,String>{'home' => teamList[1].Id,
                'homeId' => teamList[1].Id, 
                'away' => teamList[0].Id,
                'awayId' => teamList[0].Id}
        };
        calendarList[0].FTB_Pairings__c = JSON.serialize(pairings);
        insert calendarList;
    }
    @isTest
    static void getNextOpponentTest()
    {
        List<FTB_Team__c> teamList = [SELECT Id, FTB_Championship__c FROM FTB_Team__c];
        List<FTB_Calendar__c> calendarList = [SELECT Id, FTB_Championship__c, FTB_Pairings__c FROM FTB_Calendar__c];
        Test.startTest();
            FTB_WRP_Utils.HomePageHomeCalendar resultOne = FTB_UTL_Calendar.getNextOpponent(calendarList[0], teamList[0]);
            FTB_WRP_Utils.HomePageHomeCalendar resultTwo = FTB_UTL_Calendar.getNextOpponent(calendarList[0], teamList[1]);
        Test.stopTest();
        System.assertEquals(true, resultOne != null && resultTwo != null, 'Next opponent not got');
    }
   }