FTB-Community/force-app/main/default/objects/FTB_Calendar__c/FTB_Calendar__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championship game schedule and pairings</description>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Calendars</relationshipLabel>
    <relationshipName>FTB_Calendars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_EndDate__c.field-meta.xml
<CustomField>
    <fullName>FTB_EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Pairings__c.field-meta.xml
<CustomField>
    <fullName>FTB_Pairings__c</fullName>
    <label>Pairings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_StartDate__c.field-meta.xml
<CustomField>
    <fullName>FTB_StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/FTB_Player__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register player to select during championship</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Team__c.field-meta.xml
<CustomField>
    <fullName>FTB_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>FTB_Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>FTB_Players</relationshipName>
    <type>Lookup</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/FTB_Session__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track user session</description>
    <label>User Session</label>
    <nameField>
        <displayFormat>FTBS -{00000000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_SessionId__c.field-meta.xml
<CustomField>
    <fullName>FTB_SessionId__c</fullName>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>FTB_Session</relationshipLabel>
    <relationshipName>FTB_Session</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/classes/FTB_UTL_HomePageHomeTest.cls
/**@frpanico
 * Test class for FTB_UTL_HomePageHome
 */
@isTest
public with sharing class FTB_UTL_HomePageHomeTest
{
    @TestSetup
    static void setup()
    {
        List<FTB_User__c> userList = FTB_UTL_DataFactory.createUser(true, 1);
        List<FTB_Session__c> sessionList = FTB_UTL_DataFactory.createSession(true, 1, userList[0].Id);
        List<FTB_Championship__c> championshipList = FTB_UTL_DataFactory.createChampionships(true, 1);
        List<FTB_Team__c> teamList = FTB_UTL_DataFactory.createTeam(false, 2, championshipList[0].Id);
        teamList[0].FTB_User__c = userList[0].Id;
        teamList[1].FTB_User__c = userList[0].Id;
        insert teamList;
        List<FTB_Player__c> playerList = FTB_UTL_DataFactory.createPlayers(false, 4);
        playerList[0].FTB_Team__c = teamList[0].Id;
        playerList[1].FTB_Team__c = teamList[0].Id;
        playerList[2].FTB_Team__c = teamList[1].Id;
        playerList[3].FTB_Team__c = teamList[1].Id;
        insert playerList;
        List<FTB_Calendar__c> calendarList = FTB_UTL_DataFactory.createCalendar(false, 1, championshipList[0].Id);
        List<Map<String,String>> pairings = new List<Map<String,String>>{
            new Map<String,String>{'home' => teamList[0].Id, 
                'homeId' => teamList[0].id, 
                'away' => teamList[1].Id,
                'awayId' => teamList[1].id},
            new Map<String,String>{'home' => teamList[1].Id,
                'homeId' => teamList[1].Id, 
                'away' => teamList[0].Id,
                'awayId' => teamList[0].Id}
        };
        calendarList[0].FTB_Pairings__c = JSON.serialize(pairings);
        calendarList[0].FTB_StartDate__c = System.today();
        calendarList[0].FTB_EndDate__c = System.today().addDays(1);
        insert calendarList;
    }
    @isTest
    static void fetchDataTest()
    {
        List<FTB_Session__c> sessionList = [SELECT FTB_SessionId__c FROM FTB_Session__c];
        Test.startTest();
            String result = FTB_UTL_HomePageHome.fetchData(sessionList[0].FTB_SessionId__c);
        Test.stopTest();
        System.assertEquals(true, String.isNotBlank(result), 'Data not fetched');
    }
}