FTB-Community/force-app/main/default/objects/FTB_Calendar__c/FTB_Calendar__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championship game schedule and pairings</description>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Calendar__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Calendars</relationshipLabel>
    <relationshipName>FTB_Calendars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Championship__c/FTB_Championship__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track championships</description>
    <label>Championship</label>
    <nameField>
        <displayFormat>FTBCMP-{0000000}</displayFormat>
        <label>Championship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Championships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/FTB_Player__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register player to select during championship</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_FullName__c.field-meta.xml
<CustomField>
    <fullName>FTB_FullName__c</fullName>
    <formula>UPPER(FTB_FirstName__c) &amp; &quot; &quot; &amp;  UPPER(FTB_LastName__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Position__c.field-meta.xml
<CustomField>
    <fullName>FTB_Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Score__c.field-meta.xml
<CustomField>
    <fullName>FTB_Score__c</fullName>
    <label>Score (AVG)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_Team__c.field-meta.xml
<CustomField>
    <fullName>FTB_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>FTB_Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>FTB_Players</relationshipName>
    <type>Lookup</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/FTB_Team__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register teams that will partecipate to championships</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Championship__c.field-meta.xml
<CustomField>
    <fullName>FTB_Championship__c</fullName>
    <label>Championship</label>
    <referenceTo>FTB_Championship__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>FTB_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Loss__c.field-meta.xml
<CustomField>
    <fullName>FTB_Loss__c</fullName>
    <label>Loss</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Team__c/fields/FTB_Win__c.field-meta.xml
<CustomField>
    <fullName>FTB_Win__c</fullName>
    <label>Win</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_UTL_HomePageHome.cls
public with sharing class FTB_UTL_HomePageHome 
{
    private static List<Map<String,String>> teamConfigMap = new List<Map<String,String>>
    {
      new Map<String,String>{'label' => 'Team', 'fieldName' => 'team'},
      new Map<String,String>{'label' => 'Position', 'fieldName' => 'position'},
      new Map<String,String>{'label' => 'Player', 'fieldName' => 'player'},
      new Map<String,String>{'label' => 'Score (AVG)', 'fieldName' => 'score'}
    };

    private static List<Map<String,String>> championshipConfigMap = new List<Map<String,String>>
    {
      new Map<String,String>{'label' => 'Rank', 'fieldName' => 'rank'},
      new Map<String,String>{'label' => 'Team', 'fieldName' => 'team'},
      new Map<String,String>{'label' => 'Win', 'fieldName' => 'win'},
      new Map<String,String>{'label' => 'Loss', 'fieldName' => 'loss'}
    };

    public static String fetchData(String sessionId)
    {
      try
      {
        return getHomeData(sessionId);
      }
      catch(Exception e)
      {
        new FTB_UTL_ErrorLog(String.valueOf(FTB_ENM_Service.FETCH_HOME), 'HOME-0001', e.getMessage() + ' At line: ' + e.getLineNumber());
        return '';
      }
    }

    private static String getHomeData(String sessionId)
    {
        Set<Id> championshipIds = new Set<Id>();
        FTB_WRP_Utils.HomePageHomeWrp result = new FTB_WRP_Utils.HomePageHomeWrp();
  
        List<FTB_Team__c> userTeam  = FTB_QR_Team.getTeamWithPlayersByUserSession(sessionId);
        for(FTB_Team__c team : userTeam)
        {
          championshipIds.add(team.FTB_Championship__c);
        }
        List<FTB_Championship__c> championshipList = FTB_QR_Championship.getChampionshipsWithTeamsByIdSet(championshipIds);
  
        result.teamColumns = createHeader(teamConfigMap);
        result.championshipColumns = createHeader(championshipConfigMap);
        result.teamsData = createTeamData(userTeam);
        result.championshipData = createChampionshipData(championshipList);
        result.nextMatchPaylaod = createCalendarData(championshipList, userTeam);
  
        return JSON.serialize(result);
    }

    private static List<FTB_WRP_Utils.ColumnHeaderWrp> createHeader(List<Map<String, String>> configMap)
    {
        List<FTB_WRP_Utils.ColumnHeaderWrp> result = new List<FTB_WRP_Utils.ColumnHeaderWrp>();
        for(Map<String,String> keyValueSet : configMap)
        {
          FTB_WRP_Utils.ColumnHeaderWrp singleCol = new FTB_WRP_Utils.ColumnHeaderWrp();
          singleCol.label = keyValueSet.get('label');
          singleCol.fieldName = keyValueSet.get('fieldName');
          result.add(singleCol);
        }

        return result;
    }
    private static List<FTB_WRP_Utils.HomePageHomeTeam> createTeamData(List<FTB_Team__c> teamList)
    {
        List<FTB_WRP_Utils.HomePageHomeTeam> result = new List<FTB_WRP_Utils.HomePageHomeTeam>();
        for(FTB_Team__c team : teamList)
        {
          FTB_WRP_Utils.HomePageHomeTeam singleData = new FTB_WRP_Utils.HomePageHomeTeam();
          List<FTB_WRP_Utils.HomePageHomePlayer> playersData = new List<FTB_WRP_Utils.HomePageHomePlayer>();
          singleData.id = team.Id;
          singleData.team = team.Name;
          for(FTB_Player__c player : team.FTB_Players__r)
          {
            FTB_WRP_Utils.HomePageHomePlayer singlePlayerData = new FTB_WRP_Utils.HomePageHomePlayer();
            singlePlayerData.player = player.FTB_FullName__c;
            singlePlayerData.position = player.FTB_Position__c;
            singlePlayerData.score = String.valueOf(player.FTB_Score__c);
            playersData.add(singlePlayerData);
          }
          singleData.children = playersData;
          result.add(singleData);
        }

        return result;
    }
    private static List<FTB_WRP_Utils.HomePageHomeChampionship> createChampionshipData(List<FTB_Championship__c> championshipList)
    {
        List<FTB_WRP_Utils.HomePageHomeChampionship> result = new List<FTB_WRP_Utils.HomePageHomeChampionship>();
        for(FTB_Championship__c championship : championshipList)
        {
          FTB_WRP_Utils.HomePageHomeChampionship singleChampionship = new FTB_WRP_Utils.HomePageHomeChampionship();
          singleChampionship.id = championship.Id;
          singleChampionship.championshipName = championship.Name;
          List<FTB_WRP_Utils.HomePageHomeChampionshipRank> ranks = new List<FTB_WRP_Utils.HomePageHomeChampionshipRank>();
          for(FTB_Team__c team : championship.FTB_Teams__r)
          {
            FTB_WRP_Utils.HomePageHomeChampionshipRank singleRank = new FTB_WRP_Utils.HomePageHomeChampionshipRank();
            singleRank.team = team.Name;
            singleRank.rank = String.valueOf(team.FTB_Ranking__c);
            singleRank.win  = String.valueOf(team.FTB_Win__c);
            singleRank.loss = String.valueOf(team.FTB_Loss__c);
            ranks.add(singleRank);
          }
          singleChampionship.championshipRank = ranks;
          result.add(singleChampionship);
        }

        return result;
    }
    private static List<FTB_WRP_Utils.HomePageHomeCalendar> createCalendarData(List<FTB_Championship__c> championshipList, List<FTB_Team__c> teamList)
    {
      List<FTB_WRP_Utils.HomePageHomeCalendar> result = new List<FTB_WRP_Utils.HomePageHomeCalendar>();
      for(FTB_Championship__c championship : championshipList)
      {
        for(FTB_Calendar__c calendar : championship?.FTB_Calendars__r)
        {
          for(FTB_Team__c singleTeam : teamList)
          {
            FTB_WRP_Utils.HomePageHomeCalendar nextOpponent= FTB_UTL_Calendar.getNextOpponent(calendar, singleTeam);
            if(nextOpponent != null)
            {
              result.add(FTB_UTL_Calendar.getNextOpponent(calendar, singleTeam));
            }
          }
        }
      }

      return result;
    }
}