FTB-Community/force-app/main/default/objects/FTB_FieldMapper__mdt/FTB_FieldMapper__mdt.object-meta.xml
<CustomObject>
    <description>FTB custom metadata to map integration object to instances of SFDC objects</description>
    <label>Field Mapper</label>
    <pluralLabel>Field Mappers</pluralLabel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_FieldMapper__mdt/fields/FTB_FieldType__c.field-meta.xml
<CustomField>
    <fullName>FTB_FieldType__c</fullName>
    <label>Field Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_FieldMapper__mdt/fields/FTB_IntegrationField__c.field-meta.xml
<CustomField>
    <fullName>FTB_IntegrationField__c</fullName>
    <label>Integration Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_FieldMapper__mdt/fields/FTB_SfdcField__c.field-meta.xml
<CustomField>
    <fullName>FTB_SfdcField__c</fullName>
    <label>Salesforce Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_QR_Utils.cls
/**@frpanico 2022-03-06
 * FTB
 * Query class for utility items
 */
public with sharing class FTB_QR_Utils extends FTB_UTL_Utils
{
    public List<FTB_FieldMapper__mdt> getMapper(String service)
    {
        return readSObject([SELECT FTB_IntegrationField__c,
        FTB_ObjectName__c,
        FTB_SfdcField__c,
        FTB_CharacterLink__c,
        FTB_FieldType__c
        FROM FTB_FieldMapper__mdt
        WHERE FTB_Service__c = :service]);
    }
}