FTB-Community/force-app/main/default/objects/FTB_Player__c/FTB_Player__c.object-meta.xml
<CustomObject>
    <description>FTB Object to register player to select during championship</description>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Player__c/fields/FTB_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FTB_IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_UTL_DataFactory.cls
/**@frpanico 2022-03-06
 * FTB
 * Factory Class to create test data
 */
public with sharing class FTB_UTL_DataFactory
{
    public static List<FTB_Player__c> createPlayers(Boolean create, Integer numberOfRecords)
    {
        List<FTB_Player__c> players = new List<FTB_Player__c>();
        for(Integer i = 0; i < numberOfRecords; ++i)
        {   
            FTB_Player__c player = new FTB_Player__c();
            player.Name = 'Player ' + i;
            player.FTB_IsActive__c = true;
            players.add(player);
        }
        if(!players.isEmpty())
        {
            insert players;
        }
        return players;
    }
}