FTB-Community/force-app/main/default/objects/FTB_PEV_NotificationMessage__e/FTB_PEV_NotificationMessage__e.object-meta.xml
<CustomObject>
    <description>FTB Platform Event to communicate across the salesforce platform</description>
    <label>Notification Message</label>
    <pluralLabel>Notification Messages</pluralLabel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_PEV_NotificationMessage__e/fields/FTB_SerializedMessage__c.field-meta.xml
<CustomField>
    <fullName>FTB_SerializedMessage__c</fullName>
    <label>Serialized Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_PEV_NotificationMessage__e/fields/FTB_Service__c.field-meta.xml
<CustomField>
    <fullName>FTB_Service__c</fullName>
    <label>Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/FTB_Session__c.object-meta.xml
<CustomObject>
    <description>FTB Object to track user session</description>
    <label>User Session</label>
    <nameField>
        <displayFormat>FTBS -{00000000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_SessionId__c.field-meta.xml
<CustomField>
    <fullName>FTB_SessionId__c</fullName>
    <externalId>true</externalId>
    <label>Session Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_Session__c/fields/FTB_User__c.field-meta.xml
<CustomField>
    <fullName>FTB_User__c</fullName>
    <label>User</label>
    <referenceTo>FTB_User__c</referenceTo>
    <relationshipLabel>FTB_Session</relationshipLabel>
    <relationshipName>FTB_Session</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/FTB_User__c.object-meta.xml
<CustomObject>
    <description>FTB Object for registering users</description>
    <label>User</label>
    <nameField>
        <displayFormat>FTBUSR-{0000000}</displayFormat>
        <label>User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FTB-Community/force-app/main/default/objects/FTB_User__c/fields/FTB_Password__c.field-meta.xml
<CustomField>
    <fullName>FTB_Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

FTB-Community/force-app/main/default/objects/FTB_User__c/fields/FTB_Username__c.field-meta.xml
<CustomField>
    <fullName>FTB_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FTB-Community/force-app/main/default/classes/FTB_TRH_LoginMessageEvt.cls
public with sharing class FTB_TRH_LoginMessageEvt extends FTB_TRH_TriggerHandler
{
    public override void afterInsert()
    {
        FTB_LoginMessage__e event = (FTB_LoginMessage__e) Trigger.new[0];
        /* Happy Flow */
        FTB_User__c newUser = new FTB_User__c();
        FTB_Session__c newSession = new FTB_Session__c();
        Map<String, String> credentials = (Map<String, String>) JSON.deserialize(event.FTB_Payload__c, Map<String,String>.class);

        newUser.FTB_Username__c = credentials.get('username');
        newUser.FTB_Password__c = credentials.get('password');

        insertSObject(newUser);
        
        newUser = (FTB_User__c) readSObject([SELECT Id FROM FTB_User__c WHERE FTB_Username__c = :newUser.FTB_Username__c LIMIT 1])[0];

        newSession.FTB_User__c = newUser.Id;
        newSession.FTB_SessionId__c = generateSessionId(credentials.get('password'));

        insertSObject(newSession);

        FTB_Queue__c workedQueue = new FTB_Queue__c(Id = credentials.get('queueId'));
        deleteSObject(workedQueue);

        FTB_PEV_NotificationMessage__e notification = new FTB_PEV_NotificationMessage__e();
        notification.FTB_SerializedMessage__c = 'SUCCESS';
        notification.FTB_Service__c = String.valueOf(FTB_ENM_Service.SIGN);

        Eventbus.publish(notification);

    }

}